### ISSUE TITLE
Morning session's peer to peer Issue's 

### ISSUE THREAD

**Issue by AbdusSattar-70** [Atril33/world_top_languages#2]
### Hello @Atril33,

- [ ] I would like to take a moment to commend you on your great work with the project. Your hard work and attention to detail are greatly appreciated!😍😍😍

- [ ] OPTIONAL: I did notice a few typos in the README file that I thought could be easily fixed. For instance, [World Top Langauges] should be corrected to [World Top Languages]. While this is an optional suggestion, I believe that it would improve the overall quality of the project.

- [ ] Thank you again for your dedication and effort in completing this project. Keep up the great work!🎉🎉🎉🎉🎉

**Comment by Atril33** [comment]
Thank you @abdusSattar-70 for your great feedback.
